# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congtac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(blank=True, max_length=50, null=True)),
                ('diachi', models.CharField(blank=True, max_length=50, null=True)),
                ('congtac', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'congtac',
                'managed': False,
            },
        ),
    ]
