from django.db import models

# Create your models here.
class TPc(models.Model):
    #pcid = models.AutoField(primary_key= True)
    pcid = models.AutoField(primary_key=True)
    so = models.CharField(max_length=50, blank=True, null=True)
    so_in = models.CharField(max_length=50, blank=True, null=True)
    ngaychuyen = models.DateTimeField(blank=True, null=True)
    hovaten = models.CharField(max_length=250, blank=True, null=True)
    diachi = models.CharField(max_length=250, blank=True, null=True)
    thuadatso = models.CharField(max_length=250, blank=True, null=True)
    tobando = models.CharField(max_length=250, blank=True, null=True)
    dc_thuadat = models.CharField(max_length=250, blank=True, null=True)
    loaiduong = models.CharField(max_length=250, blank=True, null=True)
    hangdat = models.CharField(max_length=50, blank=True, null=True)
    vitri = models.CharField(max_length=255, blank=True, null=True)
    loaidat = models.CharField(max_length=250, blank=True, null=True)
    md_sudung = models.CharField(max_length=250, blank=True, null=True)
    th_sudung = models.CharField(max_length=50, blank=True, null=True)
    od_laudai = models.CharField(max_length=50, blank=True, null=True)
    cth_tungay = models.CharField(max_length=50, blank=True, null=True)
    cth_denngay = models.CharField(max_length=50, blank=True, null=True)
    dientich = models.CharField(max_length=250, blank=True, null=True)
    dtnt = models.CharField(max_length=250, blank=True, null=True)
    dtnt_trong_hm = models.CharField(max_length=250, blank=True, null=True)
    dtnt_tren_hm = models.CharField(max_length=250, blank=True, null=True)
    dtdt = models.CharField(max_length=250, blank=True, null=True)
    dtdt_sdr = models.CharField(max_length=250, blank=True, null=True)
    dtdt_sdc = models.CharField(max_length=250, blank=True, null=True)
    nguongoc = models.CharField(max_length=250, blank=True, null=True)
    thoidiem_sdd = models.CharField(max_length=250, blank=True, null=True)
    noptien_100 = models.NullBooleanField()
    noptien_50 = models.NullBooleanField()
    noptien_50_clld = models.NullBooleanField()
    noptien_clld = models.NullBooleanField()
    capnha = models.CharField(max_length=255, blank=True, null=True)
    dt_sannha = models.CharField(max_length=250, blank=True, null=True)
    sotangnha = models.CharField(max_length=255, blank=True, null=True)
    nguongocnha = models.CharField(max_length=255, blank=True, null=True)
    ngay_hoancong = models.CharField(max_length=50, blank=True, null=True)
    doituong_kpn = models.CharField(max_length=255, blank=True, null=True)
    doitong_btth = models.CharField(max_length=255, blank=True, null=True)
    nhanvien = models.CharField(max_length=100, blank=True, null=True)
    loaihoso = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_pc'