# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 05:20
from __future__ import unicode_literals
from django.db import migrations, models
class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='TPc',
            fields=[
                ('pcid', models.AutoField(primary_key=True, serialize=False)),
                ('so', models.CharField(blank=True, max_length=50, null=True)),
                ('so_in', models.CharField(blank=True, max_length=50, null=True)),
                ('ngaychuyen', models.DateTimeField(blank=True, null=True)),
                ('hovaten', models.CharField(blank=True, max_length=250, null=True)),
                ('diachi', models.CharField(blank=True, max_length=250, null=True)),
                ('thuadatso', models.CharField(blank=True, max_length=250, null=True)),
                ('tobando', models.CharField(blank=True, max_length=250, null=True)),
                ('dc_thuadat', models.CharField(blank=True, max_length=250, null=True)),
                ('loaiduong', models.CharField(blank=True, max_length=250, null=True)),
                ('hangdat', models.CharField(blank=True, max_length=50, null=True)),
                ('vitri', models.CharField(blank=True, max_length=255, null=True)),
                ('loaidat', models.CharField(blank=True, max_length=250, null=True)),
                ('md_sudung', models.CharField(blank=True, max_length=250, null=True)),
                ('th_sudung', models.CharField(blank=True, max_length=50, null=True)),
                ('od_laudai', models.CharField(blank=True, max_length=50, null=True)),
                ('cth_tungay', models.CharField(blank=True, max_length=50, null=True)),
                ('cth_denngay', models.CharField(blank=True, max_length=50, null=True)),
                ('dientich', models.CharField(blank=True, max_length=250, null=True)),
                ('dtnt', models.CharField(blank=True, max_length=250, null=True)),
                ('dtnt_trong_hm', models.CharField(blank=True, max_length=250, null=True)),
                ('dtnt_tren_hm', models.CharField(blank=True, max_length=250, null=True)),
                ('dtdt', models.CharField(blank=True, max_length=250, null=True)),
                ('dtdt_sdr', models.CharField(blank=True, max_length=250, null=True)),
                ('dtdt_sdc', models.CharField(blank=True, max_length=250, null=True)),
                ('nguongoc', models.CharField(blank=True, max_length=250, null=True)),
                ('thoidiem_sdd', models.CharField(blank=True, max_length=250, null=True)),
                ('noptien_100', models.NullBooleanField()),
                ('noptien_50', models.NullBooleanField()),
                ('noptien_50_clld', models.NullBooleanField()),
                ('noptien_clld', models.NullBooleanField()),
                ('capnha', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_sannha', models.CharField(blank=True, max_length=250, null=True)),
                ('sotangnha', models.CharField(blank=True, max_length=255, null=True)),
                ('nguongocnha', models.CharField(blank=True, max_length=255, null=True)),
                ('ngay_hoancong', models.CharField(blank=True, max_length=50, null=True)),
                ('doituong_kpn', models.CharField(blank=True, max_length=255, null=True)),
                ('doitong_btth', models.CharField(blank=True, max_length=255, null=True)),
                ('nhanvien', models.CharField(blank=True, max_length=100, null=True)),
                ('loaihoso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_pc',
                'managed': False,
            },
        ),
    ]
